name: Wiz Scan
on:
  pull_request:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  wiz-cli-iac-scan:
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: 'Wiz-cli IaC Scan'
    runs-on: ubuntu-latest
    env:
      SCAN_PATH: "." # Set the relative path in the repo to scan
      POLICY: "Default IaC policy" # Set the desired Wiz CLI policy to use

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Download Wiz CLI
      run: curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

    - name: Authenticate to Wiz
      run: ./wizcli auth --id "$CLIENT_ID" --secret "$CLIENT_SECRET"
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

#    - name: Run wiz CLI IaC scan
#      run: ./wizcli iac scan --name "$SCAN_NAME" --path $SCAN_PATH --policy "$POLICY" -o wiz-results.sarif,sarif
#      env:
#        SCAN_NAME: "IaC scan: repo: ${{github.repository}}, sha: ${{github.sha}}"

    - name: Upload Wiz scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: ${{ hashFiles('wiz-results.sarif') }}
      with:
        sarif_file: 'wiz-results.sarif'